export const assistantKnowledge = {
  positioning:
    "KAH-Digital conçoit des sites web, applications, automatisations IA, parcours support GLPI et outils métier pour des indépendants, PME et structures en croissance. L'assistant doit orienter vers l'offre adaptée, cadrer le besoin, donner une fourchette cohérente avec le catalogue public, puis pousser vers un devis sous 24h ou une reprise humaine quand le projet est prêt.",
  process: [
    "Orientation vers la bonne offre",
    "Cadrage du besoin et des priorités",
    "Fourchette budget et délai réalistes",
    "Devis structuré sous 24h",
    "Production, livraison, support et maintenance",
  ],
  services: [
    "Landing / portfolio",
    "Site vitrine",
    "Site corporate",
    "E-commerce",
    "Application web sur mesure",
    "Automatisation IA",
    "Application mobile",
    "Dashboard et portail",
    "Parcours support connecté à GLPI",
    "Maintenance mensuelle",
  ],
  offers: [
    {
      projectType: "landing_portfolio",
      nameFr: "Landing / Portfolio",
      nameEn: "Landing / Portfolio",
      nameDe: "Landing / Portfolio",
      price: "300–600 €",
      timelineFr: "1–2 semaines",
      timelineEn: "1–2 weeks",
      timelineDe: "1–2 Wochen",
      fitFr: "page unique, portfolio, freelance, test d'offre ou présence simple avec CTA clair",
      fitEn: "one-page site, portfolio, freelance offer, quick validation or simple online presence",
      fitDe: "Onepager, Portfolio, Freelance-Angebot, schneller Markttest oder einfache Online-Präsenz",
    },
    {
      projectType: "showcase_website",
      nameFr: "Site vitrine",
      nameEn: "Showcase site",
      nameDe: "Unternehmenswebsite",
      price: "900–1 500 €",
      timelineFr: "2–3 semaines",
      timelineEn: "2–3 weeks",
      timelineDe: "2–3 Wochen",
      fitFr: "5 à 8 pages, SEO de base, formulaire, présence professionnelle",
      fitEn: "5 to 8 pages, basic SEO, form, professional online presence",
      fitDe: "5 bis 8 Seiten, Basis-SEO, Formular, professionelle Online-Präsenz",
    },
    {
      projectType: "corporate_website",
      nameFr: "Site corporate",
      nameEn: "Corporate site",
      nameDe: "Corporate-Website",
      price: "2 200–4 500 €",
      timelineFr: "3–5 semaines",
      timelineEn: "3–5 weeks",
      timelineDe: "3–5 Wochen",
      fitFr: "site complet, design premium, blog/actualités, CRM, SEO avancé",
      fitEn: "complete site, premium design, blog/news, CRM, advanced SEO",
      fitDe: "vollständige Website, Premium-Design, Blog/News, CRM, erweitertes SEO",
    },
    {
      projectType: "ecommerce",
      nameFr: "E-commerce complet",
      nameEn: "Full e-commerce",
      nameDe: "Vollständiger E-Commerce",
      price: "3 500–9 000 €",
      timelineFr: "3–8 semaines",
      timelineEn: "3–8 weeks",
      timelineDe: "3–8 Wochen",
      fitFr: "catalogue produits, paiement Stripe, tunnel d'achat, suivi commandes",
      fitEn: "product catalogue, Stripe payment, checkout flow, order tracking",
      fitDe: "Produktkatalog, Stripe-Zahlung, Checkout, Bestellverfolgung",
    },
    {
      projectType: "web_app",
      nameFr: "Application web sur mesure",
      nameEn: "Custom web app",
      nameDe: "Maßgeschneiderte Web-App",
      price: "4 000–12 000 €",
      timelineFr: "4–10 semaines",
      timelineEn: "4–10 weeks",
      timelineDe: "4–10 Wochen",
      fitFr: "outil métier, portail, SaaS, auth, base de données, dashboard, logique métier",
      fitEn: "business tool, portal, SaaS, auth, database, dashboard, business logic",
      fitDe: "Business-Tool, Portal, SaaS, Auth, Datenbank, Dashboard, Geschäftslogik",
    },
    {
      projectType: "dashboard_portal",
      nameFr: "Dashboard / Portail",
      nameEn: "Dashboard / Portal",
      nameDe: "Dashboard / Portal",
      price: "4 000–12 000 €",
      timelineFr: "4–10 semaines",
      timelineEn: "4–10 weeks",
      timelineDe: "4–10 Wochen",
      fitFr: "tableau de bord, portail client, données, rôles, espace administrateur",
      fitEn: "dashboard, client portal, data, roles, admin area",
      fitDe: "Dashboard, Kundenportal, Daten, Rollen, Admin-Bereich",
    },
    {
      projectType: "automation_ai",
      nameFr: "Automatisation IA",
      nameEn: "AI automation",
      nameDe: "KI-Automatisierung",
      price: "1 500–8 000 €",
      timelineFr: "2–6 semaines",
      timelineEn: "2–6 weeks",
      timelineDe: "2–6 Wochen",
      fitFr: "assistant IA, traitement de documents, workflows, connexion CRM/email/Notion",
      fitEn: "AI assistant, document processing, workflows, CRM/email/Notion connections",
      fitDe: "KI-Assistent, Dokumentenverarbeitung, Workflows, CRM/E-Mail/Notion-Anbindung",
    },
    {
      projectType: "mobile_app",
      nameFr: "Application mobile",
      nameEn: "Mobile app",
      nameDe: "Mobile-App",
      price: "6 000–20 000 €",
      timelineFr: "6–12 semaines et plus",
      timelineEn: "6–12+ weeks",
      timelineDe: "6–12+ Wochen",
      fitFr: "MVP iOS/Android, comptes utilisateurs, notifications, API, logique produit",
      fitEn: "iOS/Android MVP, accounts, notifications, API, product logic",
      fitDe: "iOS/Android-MVP, Konten, Benachrichtigungen, API, Produktlogik",
    },
    {
      projectType: "glpi_assistant",
      nameFr: "Parcours support GLPI",
      nameEn: "GLPI support workflow",
      nameDe: "GLPI-Support-Workflow",
      price: "2 500–8 000 €",
      timelineFr: "2–6 semaines",
      timelineEn: "2–6 weeks",
      timelineDe: "2–6 Wochen",
      fitFr: "formulaire intelligent, qualification, ticket GLPI, suivi, base de connaissance",
      fitEn: "smart form, qualification, GLPI ticket, tracking, knowledge base",
      fitDe: "intelligentes Formular, Qualifizierung, GLPI-Ticket, Tracking, Wissensbasis",
    },
  ],
  maintenancePlans: [
    {
      nameFr: "Essentiel",
      nameEn: "Essential",
      nameDe: "Basis",
      price: "90 € / mois",
      fitFr: "mises à jour sécurité, sauvegardes, monitoring uptime, support email 48h",
      fitEn: "security updates, backups, uptime monitoring, email support within 48h",
      fitDe: "Sicherheitsupdates, Backups, Uptime-Monitoring, E-Mail-Support innerhalb von 48h",
    },
    {
      nameFr: "Confort",
      nameEn: "Comfort",
      nameDe: "Komfort",
      price: "190 € / mois",
      fitFr: "Essentiel + 2h de modifications par mois et support prioritaire 24h",
      fitEn: "Essential + 2h changes per month and priority support within 24h",
      fitDe: "Basis + 2h Änderungen pro Monat und Prioritäts-Support innerhalb von 24h",
    },
    {
      nameFr: "Pro",
      nameEn: "Pro",
      nameDe: "Pro",
      price: "390 € / mois",
      fitFr: "Confort + 5h de développement, rapport analytique et réponse jour-même",
      fitEn: "Comfort + 5h development, analytics report, same-day response",
      fitDe: "Komfort + 5h Entwicklung, Analytics-Bericht, Antwort am selben Tag",
    },
  ],
  referenceProjects: [
    {
      name: "Ashanti Beauty",
      typeFr: "site vitrine premium",
      proofFr: "vidéo hero HD, prestations, partenaires, galerie, avis, Google Maps et CTA Planity",
      proofEn: "HD hero video, services, partners, gallery, reviews, Google Maps and Planity CTAs",
      proofDe: "HD-Hero-Video, Leistungen, Partner, Galerie, Bewertungen, Google Maps und Planity-CTAs",
    },
    {
      name: "TechCash Academy",
      typeFr: "plateforme de formation avec Stripe",
      proofFr: "catalogue multi-produits, auth Supabase, checkout Stripe, espace membre et admin",
      proofEn: "multi-product catalogue, Supabase auth, Stripe checkout, member area and admin",
      proofDe: "Multi-Produkt-Katalog, Supabase-Auth, Stripe-Checkout, Mitgliederbereich und Admin",
    },
    {
      name: "MineAlert",
      typeFr: "SaaS de veille et dashboard",
      proofFr: "auth, scraping live, watchlist, alertes utilisateur, monitoring et tests E2E",
      proofEn: "auth, live scraping, watchlist, user alerts, monitoring and E2E tests",
      proofDe: "Auth, Live-Scraping, Watchlist, Nutzeralarme, Monitoring und E2E-Tests",
    },
    {
      name: "KAH Prod",
      typeFr: "site premium label musical",
      proofFr: "identité premium, artistes, sorties, clips, événements, réseaux et contacts métier",
      proofEn: "premium identity, artists, releases, videos, events, socials and business contacts",
      proofDe: "Premium-Identität, Künstler, Releases, Clips, Events, Socials und Geschäftskontakte",
    },
  ],
  faq: [
    {
      key: "delai",
      keywords: ["delai", "delais", "délai", "délais", "temps", "combien de temps", "timeline", "deadline"],
      answerFr:
        "Les délais publics actuels vont d'environ 1–2 semaines pour une landing / portfolio, 2–3 semaines pour un site vitrine, 3–5 semaines pour un site corporate, 2–6 semaines pour une automatisation IA, et 4–10 semaines pour une application web. Le délai ferme se confirme après cadrage.",
      answerEn:
        "Current public timelines are roughly 1–2 weeks for a landing / portfolio, 2–3 weeks for a showcase site, 3–5 weeks for a corporate site, 2–6 weeks for AI automation, and 4–10 weeks for a web app. The fixed timeline is confirmed after framing.",
      answerDe:
        "Aktuelle öffentliche Richtwerte: etwa 1–2 Wochen für Landing / Portfolio, 2–3 Wochen für eine Unternehmenswebsite, 3–5 Wochen für eine Corporate-Website, 2–6 Wochen für KI-Automatisierung und 4–10 Wochen für eine Web-App. Der feste Termin wird nach dem Cadrage bestätigt.",
    },
    {
      key: "services",
      keywords: ["service", "services", "offre", "offres", "what do you do", "leistungen"],
      answerFr:
        "KAH-Digital couvre landing / portfolio, site vitrine, site corporate, e-commerce, application web, automatisation IA, application mobile, dashboard, parcours support GLPI et maintenance mensuelle.",
      answerEn:
        "KAH-Digital covers landing / portfolio, showcase sites, corporate sites, e-commerce, web apps, AI automation, mobile apps, dashboards, GLPI support workflows, and monthly maintenance.",
      answerDe:
        "KAH-Digital bietet Landing / Portfolio, Unternehmenswebsites, Corporate-Websites, E-Commerce, Web-Apps, KI-Automatisierung, Mobile Apps, Dashboards, GLPI-Support-Workflows und monatliche Wartung.",
    },
    {
      key: "maintenance",
      keywords: ["maintenance", "support", "suivi", "after launch", "wartung"],
      answerFr:
        "Après livraison, trois formules existent : Essentiel à 90 € / mois, Confort à 190 € / mois et Pro à 390 € / mois. Elles couvrent mises à jour, sauvegardes, corrections légères, support et suivi selon le niveau choisi.",
      answerEn:
        "After delivery, three plans are available: Essential at €90 / month, Comfort at €190 / month, and Pro at €390 / month. They cover updates, backups, light fixes, support, and follow-up depending on the level.",
      answerDe:
        "Nach der Lieferung gibt es drei Pläne: Basis für 90 € / Monat, Komfort für 190 € / Monat und Pro für 390 € / Monat. Sie decken Updates, Backups, leichte Korrekturen, Support und Betreuung je nach Level ab.",
    },
    {
      key: "method",
      keywords: ["methode", "process", "processus", "comment", "workflow", "ablauf"],
      answerFr:
        "Le process est simple : on oriente vers la bonne offre, on cadre les priorités, on valide budget et délai réalistes, puis KAH-Digital envoie un devis clair sous 24h. L'objectif est d'acheter dans de bonnes conditions, sans flou sur le périmètre.",
      answerEn:
        "The process is simple: we route you to the right offer, frame priorities, validate realistic budget and timeline, then KAH-Digital sends a clear quote within 24h. The goal is to buy under good conditions, without a vague scope.",
      answerDe:
        "Der Ablauf ist einfach: Wir leiten zum passenden Angebot, klären Prioritäten, validieren Budget und Termin realistisch, dann sendet KAH-Digital innerhalb von 24h ein klares Angebot. Ziel ist eine saubere Kaufentscheidung ohne unklaren Scope.",
    },
    {
      key: "tarifs",
      keywords: ["tarif", "tarifs", "prix", "price", "cost", "combien", "coût", "budget", "fourchette", "preis", "kosten", "how much"],
      answerFr:
        "Fourchettes actuelles : landing / portfolio 300–600 €, site vitrine 900–1 500 €, site corporate 2 200–4 500 €, automatisation IA 1 500–8 000 €, application web 4 000–12 000 €, e-commerce complet 3 500–9 000 €, application mobile 6 000–20 000 €, parcours GLPI 2 500–8 000 €. Un devis fixe vient après cadrage.",
      answerEn:
        "Current ranges: landing / portfolio €300–600, showcase site €900–1,500, corporate site €2,200–4,500, AI automation €1,500–8,000, web app €4,000–12,000, full e-commerce €3,500–9,000, mobile app €6,000–20,000, GLPI workflow €2,500–8,000. A fixed quote comes after framing.",
      answerDe:
        "Aktuelle Spannen: Landing / Portfolio 300–600 €, Unternehmenswebsite 900–1.500 €, Corporate-Website 2.200–4.500 €, KI-Automatisierung 1.500–8.000 €, Web-App 4.000–12.000 €, vollständiger E-Commerce 3.500–9.000 €, Mobile-App 6.000–20.000 €, GLPI-Workflow 2.500–8.000 €. Ein fixes Angebot folgt nach dem Cadrage.",
    },
    {
      key: "projets",
      keywords: ["projet", "projets", "portfolio", "reference", "référence", "references", "cas client", "work", "arbeiten"],
      answerFr:
        "Références récentes : Ashanti Beauty pour un site vitrine premium, TechCash Academy pour une plateforme formation avec Stripe, MineAlert pour un SaaS dashboard, et KAH Prod pour un site premium de label musical.",
      answerEn:
        "Recent references: Ashanti Beauty for a premium showcase site, TechCash Academy for a Stripe-powered training platform, MineAlert for a dashboard SaaS, and KAH Prod for a premium music label site.",
      answerDe:
        "Aktuelle Referenzen: Ashanti Beauty für eine Premium-Unternehmenswebsite, TechCash Academy für eine Stripe-Trainingsplattform, MineAlert für ein Dashboard-SaaS und KAH Prod für eine Premium-Musiklabel-Website.",
    },
    {
      key: "glpi",
      keywords: ["glpi", "ticket", "support", "helpdesk", "itil", "incident", "itsm"],
      answerFr:
        "KAH-Digital peut créer un parcours support connecté à GLPI : formulaire intelligent, qualification automatique, création de ticket, suivi et base de connaissance. Si c'est un incident actif, l'assistant le traite comme support ; si c'est une mise en place, il le traite comme projet.",
      answerEn:
        "KAH-Digital can create a GLPI-connected support workflow: smart form, automatic qualification, ticket creation, tracking, and knowledge base. If it is an active incident, the assistant treats it as support; if it is an implementation, it treats it as a project.",
      answerDe:
        "KAH-Digital kann einen GLPI-verbundenen Support-Workflow erstellen: intelligentes Formular, automatische Qualifizierung, Ticket-Erstellung, Tracking und Wissensbasis. Bei einem aktiven Incident behandelt der Assistent es als Support, bei einer Umsetzung als Projekt.",
    },
  ],
} as const;
